### ISSUE TITLE
The settings retry strategy can never fire: condition substrings do not match the actual error message

### ISSUE THREAD

**Issue by twentynineteen** [twentynineteen/bucket#253]
## Summary

The `settings` retry strategy's condition checks for `'read'` or `'parse'` in the error message,
but both consumers throw errors with the message `'Failed to load API keys: ...'`, which contains
neither substring. The retry can never fire.

## The defect

`src/shared/lib/query-utils.ts:236-240`:

```ts
settings: {
  attempts: 1,
  delay: () => 500,
  condition: (error: unknown) => {
    const message = errorMessage(error).toLowerCase()
    return message.includes('read') || message.includes('parse')
  }
}
```

`src/features/Settings/components/SettingsPage.tsx:37`:

```ts
throw createQueryError(`Failed to load API keys: ${error}`, 'SETTINGS_LOAD')
```

`src/shared/lib/prefetch-strategies.ts:113`:

```ts
throw createQueryError(`Failed to load API keys: ${error}`, 'SETTINGS_LOAD')
```

The message `'Failed to load API keys: ...'` lowercased contains neither `'read'` nor `'parse'`.
The interpolated `${error}` might match incidentally (e.g. a 'permission denied' error mentioning
'read'), but the match is not by design.

Additionally, `'SETTINGS_LOAD'` is not a member of the `QueryError['type']` union, so the
type-first pattern introduced in #240 cannot help here either.

## Expected behaviour

The settings strategy's condition should match errors from API key loading. Options:

1. Add the substring `'load'` or `'api key'` to the condition (quick fix).
2. Add a `'settings'` type to the `QueryError['type']` union and use it at the call site, then
   check the type in the condition (matches the type-first pattern from #240).

## Notes

- The strategy has `attempts: 1`, so it would retry once with a 500ms delay. Since the condition
  never matches, no retry ever happens for a failed API key load.
- Surfaced while scoping #240 / PR #251.
- Verified against `master` at `68c559a`.
