### ISSUE TITLE
The canvas retry strategy can never fire: condition substrings do not match the actual error message

### ISSUE THREAD

**Issue by twentynineteen** [twentynineteen/bucket#252]
## Summary

The `canvas` retry strategy's condition checks for `'canvas'` or `'render'` in the error message,
but its only consumer (`usePosterframeAutoRedraw`) throws an error whose message is
`'Failed to draw posterframe: ...'`, which contains neither substring. The retry can never fire.

## The defect

`src/shared/lib/query-utils.ts:230-233`:

```ts
canvas: {
  attempts: 2,
  delay: (attempt: number) => SECONDS * attempt,
  condition: (error: unknown) => {
    const message = errorMessage(error).toLowerCase()
    return message.includes('canvas') || message.includes('render')
  }
}
```

`src/features/Upload/hooks/usePosterframeAutoRedraw.ts:52`:

```ts
throw createQueryError(`Failed to draw posterframe: ${error}`, 'DRAW_OPERATION')
```

The message `'Failed to draw posterframe: ...'` lowercased contains neither `'canvas'` nor
`'render'`. The interpolated `${error}` might contain one of those substrings incidentally, but
the match is not by design.

Additionally, `'DRAW_OPERATION'` is not a member of the `QueryError['type']` union, so the
type-first pattern introduced in #240 cannot help here either - there is no typed field to check.

## Expected behaviour

The canvas strategy's condition should match errors from posterframe draw operations. Options:

1. Add the substring `'draw'` or `'posterframe'` to the condition (quick fix).
2. Add a `'canvas'` type to the `QueryError['type']` union and use it at the call site, then
   check the type in the condition (matches the type-first pattern from #240).

## Notes

- The strategy has `attempts: 2`, so it would retry twice with increasing delay. Since the condition
  never matches, no retry ever happens for a failed posterframe draw.
- Surfaced while scoping #240 / PR #251.
- Verified against `master` at `68c559a`.
